name: advance_pdf_viewer_flutter_3
description: Updated PDF viewer for Opening PDF files in Flutter apps. Works on both Android & iOS. Compatible with Flutter 3+
version: 3.0.0
homepage: https://github.com/TechRhyme-Apps/pdf_viewer_flutter

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: 
  numberpicker: 
  path_provider:

dev_dependencies:
  lint:

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
